easy_admin:
    site_name: Conference Guestbook

    design:
        menu:
            - { route: 'homepage', label: 'Back to the Website', icone: 'home'}
            - { entity: 'Conference', label: 'Conference', icon: 'map-marker'}
            - { entity: 'Comment', label: 'Comment', icon: 'comment'}
    entities:
        Conference:
            class: App\Entity\Conference

        Comment:
            class: App\Entity\Comment
            list:
                fields:
                    - author
                    - {property : 'email', type: 'email'}
                    - {property: 'createdAt', type: 'datetime'}
                sort: ['createdAt', 'ASC']
                filters: ['conference']
            edit:
                fields:
                    - {property: 'conference'}
                    - 'author'
                    - { property: 'email', type: 'email'}
                    - text
